spring:
  application:
    name: cwa-verification-server
  profiles:
    active: internal,external
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:verification
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog.yml
server:
  max-post-size: 10000
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2,TLSv1.3
    protocol: TLS
    ciphers: >-
      TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
      TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
      TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
      TLS_AES_128_GCM_SHA256
      TLS_AES_256_GCM_SHA384
      TLS_AES_128_CCM_SHA256
    key-password: ${SSL_VERIFICATION_KEYSTORE_PASSWORD}
    key-store: ${SSL_VERIFICATION_KEYSTORE_PATH}
    key-store-password: ${SSL_VERIFICATION_KEYSTORE_PASSWORD}
    key-store-provider: SUN
    key-store-type: JKS
  servlet:
    context-path: /verification-api

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
jwt:
  server: http://localhost:8080
  enabled: false
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger
management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  health:
    probes:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

tan:
  tele:
    ratelimiting:
      count: 1000
      seconds: 3600
      threshold-in-percent: 80
    valid:
      length: 9
      hours: 1
  valid:
    days: 14
appsession:
  tancountermax: 1
entities:
  cleanup:
    days: 21
    rate: 3600000
monitoring:
  batch-size: 1
initialFakeDelayMilliseconds: 10
fakeDelayMovingAverageSamples: 5
request:
  sizelimit: 10000


cwa-testresult-server:
  url: http://localhost:8088/test-results-api
  ssl:
    enabled: false
    one-way: false
    two-way: false
    hostname-verify: false
    key-store: classpath:keystore.jks
    key-store-password: changeit
    trust-store: classpath:truststore.jks
    trust-store-password: changeit

cloud:
  aws:
    region:
      static: eu-central-1
    stack:
      auto: false
